services:

  mininet:
    build:
      context: .
      dockerfile: docker/mininet/Dockerfile

    privileged: true
    network_mode: host
    pid: host

    volumes:
      - .:/workspace

    working_dir: /workspace

    stdin_open: true
    tty: true


  controller:
    build:
      context: .
      dockerfile: docker/controllers/${CONTROLLER_ENV}/Dockerfile

    network_mode: host

    volumes:
      - .:/workspace

    working_dir: /workspace

    stdin_open: true
    tty: true
